export const DMI_APPROVED_COMPETITIONS = [
  { name: 'Premier League', country: 'England', priority: 1 },
  { name: 'Scottish Premiership', country: 'Scotland', priority: 2, aliases: ['Premiership'] },
  { name: 'UEFA Champions League', priority: 3, aliases: ['Champions League'] },
  { name: 'UEFA Europa League', priority: 4, aliases: ['Europa League'] },
  { name: 'Bundesliga', country: 'Germany', priority: 5 },
  { name: 'La Liga', country: 'Spain', priority: 6 },
  { name: 'Serie A', country: 'Italy', priority: 7 },
  { name: 'Ligue 1', country: 'France', priority: 8 },
  { name: 'Eredivisie', country: 'Netherlands', priority: 9 },
  { name: 'Scottish Championship', country: 'Scotland', priority: 10, group: 'Domestic Cup Competitions' },
  { name: 'Scottish Cup', country: 'Scotland', priority: 10, group: 'Domestic Cup Competitions' },
  { name: 'Scottish League Cup', country: 'Scotland', priority: 10, group: 'Domestic Cup Competitions', aliases: ['League Cup', 'Premier Sports Cup'] },
  { name: 'Scottish Challenge Cup', country: 'Scotland', priority: 10, group: 'Domestic Cup Competitions', aliases: ['Challenge Cup'] },
  { name: 'EFL Championship', country: 'England', priority: 10, group: 'Domestic Cup Competitions', aliases: ['Championship'] },
  { name: 'FA Cup', country: 'England', priority: 10, group: 'Domestic Cup Competitions' },
  { name: 'EFL Cup', country: 'England', priority: 10, group: 'Domestic Cup Competitions', aliases: ['League Cup', 'Carabao Cup'] },
  { name: 'DFL-Supercup', country: 'Germany', priority: 10, group: 'Domestic Cup Competitions', aliases: ['Super Cup'] },
  { name: 'Copa del Rey', country: 'Spain', priority: 10, group: 'Domestic Cup Competitions' },
  { name: 'Supercopa de Espana', country: 'Spain', priority: 10, group: 'Domestic Cup Competitions', aliases: ['Super Cup'] },
  { name: 'Coppa Italia', country: 'Italy', priority: 10, group: 'Domestic Cup Competitions' },
  { name: 'Supercoppa Italiana', country: 'Italy', priority: 10, group: 'Domestic Cup Competitions', aliases: ['Super Cup'] },
  { name: 'Coupe de France', country: 'France', priority: 10, group: 'Domestic Cup Competitions' },
  { name: 'Trophee des Champions', country: 'France', priority: 10, group: 'Domestic Cup Competitions', aliases: ['Trophée des Champions'] },
  { name: 'KNVB Cup', country: 'Netherlands', priority: 10, group: 'Domestic Cup Competitions' },
  { name: 'Johan Cruyff Shield', country: 'Netherlands', priority: 10, group: 'Domestic Cup Competitions' },
  { name: 'Eliteserien', country: 'Norway', priority: 10, group: 'Domestic Cup Competitions' },
  { name: 'UEFA Conference League', priority: 11, group: 'International Competitions', aliases: ['Conference League'] },
  { name: 'UEFA Super Cup', priority: 11, group: 'International Competitions', aliases: ['Super Cup'] },
  { name: 'FIFA World Cup', priority: 11, group: 'International Competitions', aliases: ['World Cup'] },
  { name: 'UEFA European Championship', priority: 11, group: 'International Competitions', aliases: ['Euro Championship', 'European Championship'] },
  { name: 'Africa Cup of Nations', priority: 11, group: 'International Competitions', aliases: ['AFCON'] },
  { name: 'UEFA Champions League Qualification', priority: 12, group: 'Qualification Competitions', aliases: ['Champions League Qualification'] },
  { name: 'UEFA Europa League Qualification', priority: 12, group: 'Qualification Competitions', aliases: ['Europa League Qualification'] },
  { name: 'UEFA Conference League Qualification', priority: 12, group: 'Qualification Competitions', aliases: ['Conference League Qualification'] },
  { name: 'UEFA European Championship Qualification', priority: 12, group: 'Qualification Competitions', aliases: ['Euro Championship Qualification'] },
  { name: 'Africa Cup of Nations Qualification', priority: 12, group: 'Qualification Competitions', aliases: ['AFCON Qualification'] },
  { name: 'FIFA Club World Cup', priority: 13, group: 'FIFA Club World Cup Competitions', aliases: ['Club World Cup'] },
  { name: 'FIFA Club World Cup Qualification', priority: 13, group: 'FIFA Club World Cup Competitions', aliases: ['Club World Cup Qualification'] },
];

export const DMI_STANDARD_COUPON_SIZE = 20;
